# --- !Ups
CREATE SEQUENCE CHALLENGE_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE CHALLENGE_PART_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE CHALLENGE_RESP_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE USERS_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE COMMENTS_SEQ INCREMENT BY 1 START WITH 1;

CREATE SEQUENCE NOTIFICATIONS_SEQ INCREMENT BY 1 START WITH 1;

# --- !Downs
DROP SEQUENCE CHALLENGE_SEQ;
DROP SEQUENCE CHALLENGE_PART_SEQ;
DROP SEQUENCE CHALLENGE_RESP_SEQ;
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE NOTIFICATIONS_SEQ;