package domain;

/**
 * Created by jasbuber on 2014-04-11.
 */
public enum ChallengeCategory {
    ALL, FOOD_COMA, EARGASMIC, DRINKING_ZONE, FREAK_MODE, GIVING_BACK, FITNESS_AVENUE, MIND_GAMES, AQUA_SPHERE, OTHER,
    FOOD, STAYING_ACTIVE, USING_A_BRAIN, GETTING_INVOLVED
}
